version: "3"

services:
    client:
        image: nginx
        ports:
            - 7000:80
        volumes:
            - ./:/usr/share/nginx/html
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge
